from typing import Protocol
from .types import Point

class UiPort(Protocol):
    def focus(self, target: Point) -> None: ...
    def click(self, target: Point, button: str = "left", offset: tuple[int,int] | None = None) -> None: ...
    def double(self, target: Point) -> None: ...
    def drag(self, start: Point, end: Point) -> None: ...
    def scroll(self, amount: int, axis: str = "vertical") -> None: ...
    def type_text(self, text: str) -> None: ...
    def paste(self, text: str, clear: bool = False) -> None: ...
    def press(self, keys: str) -> None: ...
    def navigate(self, url: str) -> None: ...
