# PS-SB-PORTS-STUB v1.1 — crash-safe (quiet build/test + logfile)
$ErrorActionPreference = "Stop"
function Warn($m){ Write-Host "[경고] $m" -ForegroundColor DarkYellow }
function Info($m){ Write-Host "[정보] $m" -ForegroundColor Cyan }
function Pass($m){ Write-Host "[PASS]  $m" -ForegroundColor Green }
function Fail($m){ Write-Host "[FAIL]  $m" -ForegroundColor Red; exit 2 }

# 0) 경로/로그
$repo = (Get-Location).Path
if(-not (Test-Path ".\package.json")){ Fail "여기 repo 아님: $repo" }
mkdir -Force .\logs | Out-Null
$log = ".\logs\ports_stub_{0:yyyyMMdd-HHmmss}.log" -f (Get-Date)
Info ("로그: {0}" -f $log)

# 1) 포트 파일 보강
$portsPath = ".\domain\reporting\ports.ts"
if(-not (Test-Path (Split-Path $portsPath -Parent))){ New-Item -ItemType Directory -Path (Split-Path $portsPath -Parent) | Out-Null }

if(-not (Test-Path $portsPath)){
@"
// Auto-generated by PS-SB-PORTS-STUB v1.1
export interface ParsePort {}
export interface QueryPort {}
export interface RenderPort {}
"@ | Set-Content -Path $portsPath -Encoding UTF8
  Info ("신규 생성: {0}" -f $portsPath)
} else {
  $txt = Get-Content $portsPath -Raw
  $added = $false
  if($txt -notmatch 'export\s+interface\s+ParsePort\b'){ Add-Content -Path $portsPath -Value "`nexport interface ParsePort {}"; $added=$true; Warn "ParsePort 추가" }
  if($txt -notmatch 'export\s+interface\s+QueryPort\b'){ Add-Content -Path $portsPath -Value "`nexport interface QueryPort {}"; $added=$true; Warn "QueryPort 추가" }
  if($txt -notmatch 'export\s+interface\s+RenderPort\b'){ Add-Content -Path $portsPath -Value "`nexport interface RenderPort {}"; $added=$true; Warn "RenderPort 추가" }
  if(-not $added){ Info "ports.ts 이미 필요한 export 존재" }
}

# 2) 조용 빌드/테스트 (과다 출력 → 로그에만 기록)
"== BUILD =="  | Out-File -FilePath $log -Encoding UTF8
& npm.cmd run build --silent *>> $log
if($LASTEXITCODE -ne 0){ Get-Content $log -Tail 120 | Write-Host -ForegroundColor DarkYellow; Fail "build 실패" }

"== TESTS =="  | Out-File -FilePath $log -Append
& npm.cmd run run-tests --silent *>> $log
if($LASTEXITCODE -ne 0){ Get-Content $log -Tail 120 | Write-Host -ForegroundColor DarkYellow; Fail "tests 실패" }

# 3) 커밋/푸시
git add $portsPath
$branch = (git rev-parse --abbrev-ref HEAD); if([string]::IsNullOrWhiteSpace($branch)){ $branch="main" }
git commit -m "fix(domain-ports): add missing exports (ParsePort/QueryPort/RenderPort) [PS-SB-PORTS-STUB v1.1]" --allow-empty
git push origin $branch

Pass ("완료 — 빌드/테스트 통과 + 푸시({0})" -f $branch)
Pass ("로그 확인: {0}" -f $log)
