name: release-verify

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to verify (e.g. v0.1.22)"
        required: false
  push:
    tags:
      - "v*.*.*"
  release:
    types: [published, edited]

jobs:
  notes-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Resolve TAG
        id: resolve
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" = "release" ]; then
            echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          elif [ "${{ github.ref_type }}" = "tag" ]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          fi
          echo "TAG=$TAG"
      - name: Generate notes via ACL
        run: |
          node scripts/acl/release-notes.mjs --tag="$TAG" --out="out/release_notes/$TAG.md"
      - name: Fetch release body
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p out/release_notes
          gh api "repos/${{ github.repository }}/releases/tags/$TAG" -q .body > out/release_notes/_remote_body.txt
      - name: Compare (normalize & diff)
        run: |
          sed -e 's/\r$//' "out/release_notes/$TAG.md" > out/local.txt
          sed -e 's/\r$//' "out/release_notes/_remote_body.txt" > out/remote.txt
          diff -u out/remote.txt out/local.txt || (echo "::error::Mismatch between GitHub Release body and local notes"; exit 1)
      - name: Upload diff (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: release-notes-diff
          path: out/release_notes/_diff.patch

