name: AK7 (always-on)

on:
  issue_comment:
    types: [created, edited]   # 댓글 생성/수정 모두 잡음
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number to comment on"
        required: true
      body:
        description: "Comment body to simulate"
        required: true

permissions:
  contents: read
  issues: write
  pull-requests: write
  checks: write

jobs:
  # 0) 어떤 경우든 '항상' 뜨는 트리거 잡
  trigger:
    runs-on: ubuntu-latest
    outputs:
      body: ${{ steps.out.outputs.body }}
      kind: ${{ steps.out.outputs.kind }}
    steps:
      - id: out
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            b="${{ inputs.body }}"
          else
            b="${{ github.event.comment.body }}"
          fi
          echo "body=$b"  >> $GITHUB_OUTPUT
          if [[ "$b" == /ak* ]];   then echo "kind=ak"   >> $GITHUB_OUTPUT; fi
          if [[ "$b" == /ping* ]]; then echo "kind=ping" >> $GITHUB_OUTPUT; fi
      - name: Note
        run: echo "triggered with body='${{ steps.out.outputs.body }}' kind='${{ steps.out.outputs.kind }}'"

  # 1) ack 댓글(둘 다 공통)
  ack:
    needs: trigger
    if: ${{ needs.trigger.outputs.kind == 'ak' || needs.trigger.outputs.kind == 'ping' }}
    runs-on: ubuntu-latest
    outputs:
      body: ${{ steps.capture.outputs.body }}
    steps:
      - id: capture
        run: echo "body=${{ needs.trigger.outputs.body }}" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const body = `${{ toJson(needs.trigger.outputs.body) }}`.trim();
            const issue = context.eventName === 'workflow_dispatch'
              ? Number("${{ inputs.issue_number }}")
              : context.payload.issue.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner, repo: context.repo.repo,
              issue_number: issue,
              body: `ack ✅ ${body} (event=${context.eventName})`
            });

  # 2) /ping은 여기서 종료
  done:
    needs: [trigger, ack]
    if: ${{ needs.trigger.outputs.kind == 'ping' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "ping handled."

  # 3) /ak이면 Windows에서 실제 실행(+ 실패해도 tail 댓글 보장)
  run:
    needs: [trigger, ack]
    if: ${{ needs.trigger.outputs.kind == 'ak' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse
        id: parse
        shell: pwsh
        run: |
          $p = "${{ needs.ack.outputs.body }}".Trim().Split(' ',[System.StringSplitOptions]::RemoveEmptyEntries)
          "cmd=$($p[1] ?? 'scan')"     | Out-File $env:GITHUB_OUTPUT -Append
          "mode=$($p[2] ?? 'preview')" | Out-File $env:GITHUB_OUTPUT -Append
          New-Item -ItemType File -Force .ak-out.txt | Out-Null

      - name: Run AK task
        id: runstep
        shell: pwsh
        env: { AK_MODE: ${{ steps.parse.outputs.mode }} }
        run: |
          Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'
          $map=@{ scan='ak-scan.ps1'; rewrite='ak-rewrite.ps1'; fix='ak-fixloop.ps1'; test='ak-test.ps1'; fixloop='ak-fixloop.ps1' }
          $cmd='${{ steps.parse.outputs.cmd }}'
          if(-not $map.ContainsKey($cmd)){ "Unknown: $cmd" | Tee-Object .ak-out.txt -Append; exit 10 }

          $cand=@(
            Join-Path 'scripts/g5' $map[$cmd],
            Join-Path 'scripts'    $map[$cmd],
            $map[$cmd]
          ) | ? { Test-Path $_ } | Select-Object -First 1
          if(-not $cand){ "Script not found: $($map[$cmd])" | Tee-Object .ak-out.txt -Append; exit 11 }

          $supportsMode = try { (Get-Command $cand -ErrorAction Stop).Parameters.ContainsKey('Mode') } catch { $false }
          $args=@(); if($supportsMode){ $args += @('-Mode',$env:AK_MODE) }

          ">> Running $cand $args" | Tee-Object .ak-out.txt -Append
          try { & pwsh -NoProfile -File $cand @args 2>&1 | Tee-Object .ak-out.txt -Append; $code=$LASTEXITCODE }
          catch { $_ | Out-String | Tee-Object .ak-out.txt -Append; $code=1 }
          "exit_code=$code" | Out-File $env:GITHUB_OUTPUT -Append
          if($code -ne 0){ Write-Error "AK step failed with code $code" }

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ak7-logs
          path: |
            .ak-out.txt
            logs/**/*.log
          if-no-files-found: ignore

      - name: Reply with tail
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
        env:
          CMD:  ${{ steps.parse.outputs.cmd }}
          MODE: ${{ steps.parse.outputs.mode }}
        script: |
          const fs = require('fs');
          let tail = '(no .ak-out.txt)';
          try { tail = fs.readFileSync('.ak-out.txt','utf8').split('\n').slice(-100).join('\n'); } catch {}
          const issue = context.eventName === 'workflow_dispatch'
            ? Number("${{ inputs.issue_number }}")
            : context.payload.issue.number;
          await github.rest.issues.createComment({
            owner: context.repo.owner, repo: context.repo.repo,
            issue_number: issue,
            body: `✅ \`/ak\` done (${process.env.CMD} ${process.env.MODE})\n\n\`\`\`\n${tail}\n\`\`\``
          });
