name: AK7 run (/ak only, robust)

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ak-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  ak:
    # 봇이 남긴 댓글은 무시, /ak 로 시작하는 댓글만 처리
    if: >
      github.event.comment.user.login != 'github-actions' &&
      startsWith(github.event.comment.body, '/ak')
    runs-on: ubuntu-latest

    steps:
      - name: Gate
        id: gate
        run: |
          echo "BODY<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.comment.body }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          if [ "${{ github.event.issue.pull_request }}" = "" ]; then
            echo "isPR=0" >> $GITHUB_OUTPUT
          else
            echo "isPR=1" >> $GITHUB_OUTPUT
          fi

      - name: Ack
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.comment.body.trim();
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: `ack ✅ "${body}" (exec stable)`
            });

      # PR이 아니면 안내만 남기고 종료
      - name: Info (PR only)
        if: steps.gate.outputs.isPR == '0'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: `ℹ️ \`/ak\` 실행은 **PR 대화**에서만 동작합니다. 현재는 Issue라 git 실행을 스킵했어요.`
            });

      # 간단 요약(아티팩트)
      - name: Write summary
        run: |
          {
            echo "| key | value |"
            echo "|---|---|"
            echo "| event | issue_comment |"
            echo "| isAK | 1 |"
            echo "| issue | ${{ github.event.issue.number }} |"
            echo "| body | ${{ steps.gate.outputs.BODY }} |"
          } > xp-summary.md
      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: xp-summary
          path: xp-summary.md
