name: AK7 run (/ak only)

on:
  issue_comment:               { types: [created, edited] }
  pull_request_review_comment: { types: [created, edited] }
  workflow_dispatch:
    inputs:
      issue_number: { description: "Issue/PR number", required: true }
      body:         { description: "Comment body to simulate", required: true }

permissions:
  contents: read
  issues: write
  pull-requests: write
  checks: write

jobs:
  # 항상 뜨는 게이트 (여기서만 필터링) ── "아무 반응 없음" 방지
  gate:
    runs-on: ubuntu-latest
    outputs:
      body:  ${{ steps.out.outputs.body }}
      is_ak: ${{ steps.out.outputs.is_ak }}
      issue: ${{ steps.out.outputs.issue }}
    steps:
      - id: out
        shell: bash
        run: |
          # 1) 본문/타깃 이슈 번호 확보 (이벤트/수동 모두)
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            body="${{ inputs.body }}"
            issue="${{ inputs.issue_number }}"
          else
            body="${{ github.event.comment.body }}"
            issue=""  # 아래 JS에서 안전하게 계산
          fi
          body_trim="$(printf '%s' "$body" | sed -e 's/^[[:space:]]*//' )"
          is_ak="0"; case "$body_trim" in (/ak*|/AK*) is_ak="1";; esac
          echo "body=$body_trim" >> $GITHUB_OUTPUT
          echo "is_ak=$is_ak"    >> $GITHUB_OUTPUT
          echo "issue=$issue"    >> $GITHUB_OUTPUT
      - name: note
        run: echo "gate: body='${{ steps.out.outputs.body }}' is_ak='${{ steps.out.outputs.is_ak }}'"

  # ack 댓글 (PR 줄댓글/이슈댓글 모두 지원; 이슈번호를 안전하게 계산)
  ack:
    needs: gate
    if: ${{ needs.gate.outputs.is_ak == '1' }}
    runs-on: ubuntu-latest
    outputs:
      body:  ${{ steps.cap.outputs.body }}
      issue: ${{ steps.cap.outputs.issue }}
    steps:
      - id: cap
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            // 1) 본문
            const body = `${{ toJson(needs.gate.outputs.body) }}`.trim();

            // 2) 타깃 번호 계산 (이슈댓글/PR 대화/PR 줄댓글 모두)
            let issue = `${{ needs.gate.outputs.issue }}` || "";
            if (!issue) {
              const p = context.payload;
              // issue_comment: 이슈나 PR 대화 탭
              if (p.issue && p.issue.number) {
                issue = String(p.issue.number);
              }
              // pull_request_review_comment: 코드 줄댓글 (PR 번호는 URL에서 추출)
              else if (p.comment && p.comment.pull_request_url) {
                const m = p.comment.pull_request_url.match(/\/pulls\/(\d+)(?:$|[/?#])/);
                if (m) issue = m[1];
              }
            }
            if (!issue) {
              core.setFailed("Cannot resolve issue/PR number for replying.");
              return;
            }

            core.setOutput("body", body);
            core.setOutput("issue", issue);

            // 3) ACK 댓글
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(issue),
              body: `ack ✅ ${body}`
            });

  # Windows에서 실제 실행 (+ 실패해도 tail은 보장)
  run:
    needs: ack
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse
        id: parse
        shell: pwsh
        run: |
          $p = "${{ needs.ack.outputs.body }}".Trim().Split(' ',[System.StringSplitOptions]::RemoveEmptyEntries)
          "cmd=$($p[1] ?? 'scan')"     | Out-File $env:GITHUB_OUTPUT -Append
          "mode=$($p[2] ?? 'preview')" | Out-File $env:GITHUB_OUTPUT -Append
          New-Item -ItemType File -Force .ak-out.txt | Out-Null

      - name: Run AK task
        id: runstep
        shell: pwsh
        env: { AK_MODE: ${{ steps.parse.outputs.mode }} }
        run: |
          Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'
          $map=@{ scan='ak-scan.ps1'; rewrite='ak-rewrite.ps1'; fix='ak-fixloop.ps1'; test='ak-test.ps1'; fixloop='ak-fixloop.ps1' }
          $cmd='${{ steps.parse.outputs.cmd }}'
          if(-not $map.ContainsKey($cmd)){ "Unknown: $cmd" | Tee-Object .ak-out.txt -Append; exit 10 }

          $cand=@(
            Join-Path 'scripts/g5' $map[$cmd],
            Join-Path 'scripts'    $map[$cmd],
            $map[$cmd]
          ) | ? { Test-Path $_ } | Select-Object -First 1
          if(-not $cand){ "Script not found: $($map[$cmd])" | Tee-Object .ak-out.txt -Append; exit 11 }

          $supportsMode = try { (Get-Command $cand -ErrorAction Stop).Parameters.ContainsKey('Mode') } catch { $false }
          $args=@(); if($supportsMode){ $args += @('-Mode',$env:AK_MODE) }

          ">> Running $cand $args" | Tee-Object .ak-out.txt -Append
          try { & pwsh -NoProfile -File $cand @args 2>&1 | Tee-Object .ak-out.txt -Append; $code=$LASTEXITCODE }
          catch { $_ | Out-String | Tee-Object .ak-out.txt -Append; $code=1 }
          "exit_code=$code" | Out-File $env:GITHUB_OUTPUT -Append
          if($code -ne 0){ Write-Error "AK step failed with code $code" }

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ak7-logs
          path: |
            .ak-out.txt
            logs/**/*.log
          if-no-files-found: ignore

      - name: Reply with tail
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
        env:
          CMD:  ${{ steps.parse.outputs.cmd }}
          MODE: ${{ steps.parse.outputs.mode }}
        script: |
          const fs = require('fs');
          let tail='(no .ak-out.txt)'; try { tail = fs.readFileSync('.ak-out.txt','utf8').split('\n').slice(-100).join('\n'); } catch {}
          await github.rest.issues.createComment({
            owner: context.repo.owner, repo: context.repo.repo,
            issue_number: Number("${{ needs.ack.outputs.issue }}"),
            body: `✅ \`/ak\` done (${process.env.CMD} ${process.env.MODE})\n\n\`\`\`\n${tail}\n\`\`\``
          });
