name: AK7 run (/ak only, robust)

on:
  # CHANGED: created만 사용해 중복 실행 완화
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

# CHANGED: 댓글을 쓰지 않으므로 최소 권한
permissions:
  contents: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.run_id }}
  cancel-in-progress: true

jobs:
  ak:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      # 게이트: /ak 인지 + 원문/대상 번호
      - id: gate
        shell: pwsh
        env:
          EV_BODY:  ${{ github.event.comment.body }}
          EV_ISSUE: ${{ github.event.issue.number }}
          EV_PRNUM: ${{ github.event.pull_request.number }}
        run: |
          $body  = @"
          $env:EV_BODY
          "@.Trim()
          $issue = $env:EV_ISSUE; if (-not $issue) { $issue = $env:EV_PRNUM }
          $isAK  = if ($body -match '(?is)(^|[\s`>])/ak(\b|[\s`])') { '1' } else { '0' }

          "isAK=$isAK"   | Out-File $env:GITHUB_OUTPUT -Append
          "issue=$issue" | Out-File $env:GITHUB_OUTPUT -Append
          "body=$body"   | Out-File $env:GITHUB_OUTPUT -Append

      # PR 여부/헤드 정보
      - name: detect PR
        id: pr
        uses: actions/github-script@v7
        env:
          AK_ISSUE: ${{ steps.gate.outputs.issue }}
        with:
          github-token: ${{ github.token }}
          script: |
            let isPR='0', headRepo='', headRef='', headSha='';
            try {
              const {data} = await github.rest.pulls.get({
                owner: context.repo.owner, repo: context.repo.repo,
                pull_number: Number(process.env.AK_ISSUE)
              });
              isPR='1'; headRepo=data.head.repo.full_name; headRef=data.head.ref; headSha=data.head.sha;
            } catch {}
            core.setOutput('isPR', isPR);
            core.setOutput('headRepo', headRepo);
            core.setOutput('headRef',  headRef);
            core.setOutput('headSha',  headSha);

      # 요약 카드 (댓글 아님)
      - name: summary
        shell: pwsh
        env:
          ISAK:   ${{ steps.gate.outputs.isAK }}
          ISSUE:  ${{ steps.gate.outputs.issue }}
          BODY:   ${{ steps.gate.outputs.body }}
          ISPR:   ${{ steps.pr.outputs.isPR }}
          HREPO:  ${{ steps.pr.outputs.headRepo }}
          HREF:   ${{ steps.pr.outputs.headRef }}
          HSHA:   ${{ steps.pr.outputs.headSha }}
        run: |
          $lines = @()
          $lines += "# gate"
          $lines += ""
          $lines += "| key   | value |"
          $lines += "|-------|-------|"
          $lines += "| event | issue_comment |"
          $lines += "| isAK  | $env:ISAK |"
          $lines += "| issue | $env:ISSUE |"
          $lines += "| body  | `$env:BODY` |"
          $lines += ""
          $lines += "## pr"
          $lines += ""
          $lines += "| key   | value |"
          $lines += "|-------|-------|"
          $lines += "| isPR  | $env:ISPR |"
          $lines += "| head  | $env:HREPO@$env:HREF ($env:HSHA) |"
          $lines -join "`n" | Out-File -Encoding utf8 $env:GITHUB_STEP_SUMMARY

      # 경량 아티팩트 유지(xp-summary 등 활용 가능)
      - name: write xp-summary
        shell: pwsh
        env:
          ISAK:   ${{ steps.gate.outputs.isAK }}
          ISSUE:  ${{ steps.gate.outputs.issue }}
          BODY:   ${{ steps.gate.outputs.body }}
          ISPR:   ${{ steps.pr.outputs.isPR }}
          HREPO:  ${{ steps.pr.outputs.headRepo }}
          HREF:   ${{ steps.pr.outputs.headRef }}
          HSHA:   ${{ steps.pr.outputs.headSha }}
        run: |
          $obj = [ordered]@{
            workflow = "ak-run"
            event    = "issue_comment"
            isAK     = $env:ISAK
            issue    = $env:ISSUE
            body     = $env:BODY
            pr       = [ordered]@{
              isPR   = $env:ISPR
              head   = "$env:HREPO@$env:HREF"
              sha    = $env:HSHA
            }
          }
          ($obj | ConvertTo-Json -Depth 5) | Out-File -Encoding utf8 xp-summary.json

      - uses: actions/upload-artifact@v4
        with:
          name: xp-summary
          path: xp-summary.json
          if-no-files-found: error
