name: AK7 run (/ak only, robust)

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: ak-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  ak:
    # /ak 로 시작하는 댓글에만 반응
    if: startsWith(github.event.comment.body, '/ak ')
    runs-on: ubuntu-latest

    steps:
      - name: Parse command & gate
        id: gate
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.comment.body.trim()
            const m = body.match(/^\/ak\s+(\w+)/i)
            const cmd = (m && m[1]) ? m[1].toLowerCase() : 'scan'
            const isPR = !!context.payload.issue.pull_request
            core.setOutput('cmd', cmd)
            core.setOutput('isPR', isPR ? '1' : '0')
            core.setOutput('issue', String(context.payload.issue.number))

      - name: Ack (PR)
        if: steps.gate.outputs.isPR == '1'
        uses: actions/github-script@v7
        with:
          script: |
            const cmd = '${{ steps.gate.outputs.cmd }}'
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: `ack ✅ "/ak ${cmd}"`
            });

      - name: 안내 (Issue일 때만)
        if: steps.gate.outputs.isPR != '1'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: "ℹ️ `/ak` 실행은 PR 대화에서만 동작합니다. 현재는 Issue라 git 실행을 스킵했어요."
            });

      - name: Save tiny summary (optional)
        if: steps.gate.outputs.isPR == '1'
        run: |
          printf "event\tissue_comment\nisAK\t1\nissue\t${{ steps.gate.outputs.issue }}\nbody\t${{ github.event.comment.body }}\n" > xp-summary.tsv
      - if: steps.gate.outputs.isPR == '1'
        uses: actions/upload-artifact@v4
        with:
          name: xp-summary
          path: xp-summary.tsv
