name: Auto GitHub Release from CHANGELOG
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract release notes from CHANGELOG.md
        id: notes
        shell: bash
        run: |
          set -euo pipefail
          TAG="${GITHUB_REF_NAME}"
          if [[ -f CHANGELOG.md ]]; then
            awk -v tag="$TAG" '
              $0 ~ "^## "tag" " { flag=1; print; next }
              /^## v[0-9]+\.[0-9]+\.[0-9]+/ && flag { exit }
              flag { print }
            ' CHANGELOG.md > _notes.md || true
          fi
          if [[ ! -s _notes.md ]]; then
            echo "Patch release ${TAG}" > _notes.md
          fi
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
      - name: Create GitHub Release (idempotent)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          TAG="${{ steps.notes.outputs.tag }}"
          if gh release view "$TAG" >/dev/null 2>&1; then
            echo "Release already exists: $TAG"
          else
            gh release create "$TAG" -t "kobong-orchestrator $TAG" -F _notes.md
          fi
