name: Contracts CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  contracts:
    name: Contracts v1
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show environment
        shell: pwsh
        run: |
          $PSVersionTable
          git --version

      - name: Run contract tests
        shell: pwsh
        run: pwsh -File scripts/run-contract-tests.ps1

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out-artifacts
          path: |
            out/dsl_request.demo.json
            out/report_result.dsl.json
            out/report_result.dsl.csv
          if-no-files-found: ignore
