name: contracts-status

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  statuses: write

jobs:
  contracts-status:
    name: Windows, Python 3.11
    runs-on: windows-latest
    steps:
      - name: Set PYTHONPATH
        shell: bash
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/src:$GITHUB_WORKSPACE/tools/kobong_logger_cli:$GITHUB_WORKSPACE/tools/kobong_logger_cli/src" >> $GITHUB_ENV      - name: Set pending status
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.pull_request.head.sha;
            await github.request('POST /repos/{owner}/{repo}/statuses/{sha}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state: 'pending',
              context: 'contracts (Windows, Python 3.11)',
              description: 'Contracts check running...'
            });

      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Quick sanity step
        shell: pwsh
        run: |
          python -V
          Write-Host 'Contracts basic check OK'

      - name: Set success status
        if: ${{ success() }}
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.pull_request.head.sha;
            await github.request('POST /repos/{owner}/{repo}/statuses/{sha}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state: 'success',
              context: 'contracts (Windows, Python 3.11)',
              description: 'Contracts check passed'
            });

      - name: Set failure status
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.pull_request.head.sha;
            await github.request('POST /repos/{owner}/{repo}/statuses/{sha}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state: 'failure',
              context: 'contracts (Windows, Python 3.11)',
              description: 'Contracts check failed'
            });

