# NO-SHELL
name: contract-tests

on:
  push:
    branches:
      - ops/health-monitor-20250915-082721
      - ops/**
      - feature/**
      - main
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  contract:
    name: contract
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      - name: Install
        run: npm ci
        env:
          CI: true
          npm_config_fund: "false"
          npm_config_audit: "false"

      - name: Run contract tests
        run: npm run run-contract --if-present
        env:
          CI: true
          FORCE_COLOR: "0"
          NO_COLOR: "1"
          NODE_ENV: test

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: contract-logs
          path: |
            logs/**
            **/junit*.xml
          if-no-files-found: ignore