name: contract-tests
on:
  push:
    paths:
      - 'contracts/**'
      - 'skills/**'
      - 'tests/contract/**'
      - 'scripts/**'
      - 'project.decl.yaml'
  workflow_dispatch:

jobs:
  contract:
    runs-on: windows-latest
    steps:
      - name: Set PYTHONPATH
        shell: bash
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/src:$GITHUB_WORKSPACE/tools/kobong_logger_cli:$GITHUB_WORKSPACE/tools/kobong_logger_cli/src" >> $GITHUB_ENV      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Run contract tests
        shell: pwsh
        run: |
          pwsh -NoLogo -File scripts/run-contract-tests.ps1
