name: contracts
on:
  push:
    branches: [ main ]
    paths:
      - "contracts/**"
      - "skills/**"
      - "tests/contract/**"
      - "scripts/**"
      - "pytest.ini"
  pull_request:
    branches: [ main ]
jobs:
  contract-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set PYTHONPATH
        shell: bash
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/src:$GITHUB_WORKSPACE/tools/kobong_logger_cli:$GITHUB_WORKSPACE/tools/kobong_logger_cli/src" >> $GITHUB_ENV      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps (pinned)
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest==8.3.2 jsonschema==4.23.0 PyYAML==6.0.2
      - name: Run contract tests
        run: |
          pytest -q tests/contract

