name: guard-logs-ignored
on:
  pull_request:
  push:
permissions:
  contents: read
  statuses: write
jobs:
  no-tracked-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: scan
        shell: bash
        run: |
          set -euo pipefail
          found="$(git ls-files 'logs/*' | grep -v '^logs/.gitkeep$' || true)"
          {
            echo "found<<EOF"
            echo "$found"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
      - name: Set commit status (guard-logs-ignored/no-tracked-logs)
        uses: actions/github-script@v7
        with:
          script: |
            const found = core.getInput('found') || '';
            const has = found.trim().length > 0;
            const state = has ? 'failure' : 'success';
            const desc  = has ? 'logs/ contains tracked files (except .gitkeep)' : 'no tracked files under logs/';
            await github.request('POST /repos/{owner}/{repo}/statuses/{sha}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha:   context.sha,
              state,
              context: 'guard-logs-ignored/no-tracked-logs',
              description: desc
            });
            if (has) core.setFailed('Tracked files under logs/:\n' + found);
          found: ${{ steps.scan.outputs.found }}