name: "guard-logs-ignored/no-tracked-logs"
on:
  pull_request:
    branches: [ "main" ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure logs/ not tracked
        shell: pwsh
        run: |
          $files = git ls-files -- 'logs/*'
          if ($files) {
            Write-Host "Tracked logs found:`n$files"
            Write-Error "logs/ files must be ignored and untracked"
          } else {
            Write-Host "OK: no tracked logs"
          }