# NO-SHELL
name: housekeeping-smoke
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 6"   # 매주 일요일 KST 03:00 ~= UTC 토 18:00
jobs:
  smoke:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PowerShell 7
        uses: PowerShell/installer@v1
        with:
          version: "7.4.4"
      - name: Dry-run housekeeping weekly
        shell: pwsh
        run: |
          pwsh -NoLogo -NoProfile -File "scripts/g5/housekeeping-weekly.ps1" -Root . -TimeoutSec 60 -InactivitySec 20
      - name: Upload apply-log.jsonl (if present)
        uses: actions/upload-artifact@v4
        with:
          name: housekeeping-logs
          path: logs/apply-log.jsonl
          if-no-files-found: warn