name: Inventory • DocsManifest Guard

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '35 17 * * *'   # 매일 KST 02:35

permissions:
  contents: write   # API 커밋 용도

jobs:
  inventory:
    runs-on: windows-latest
    steps:
      - name: Download source (zipball) to workspace
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA:  ${{ github.sha }}
        run: |
          $ErrorActionPreference='Stop'
          $zip = Join-Path $env:RUNNER_TEMP 'src.zip'
          $tmp = Join-Path $env:RUNNER_TEMP 'src-unzip'
          Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Force -Path $tmp | Out-Null
          $headers = @{ Authorization="Bearer $env:GH_TOKEN"; "User-Agent"="actions"; "X-GitHub-Api-Version"="2022-11-28" }
          $uri = "https://api.github.com/repos/$env:REPO/zipball/$env:SHA"
          Invoke-WebRequest -Uri $uri -Headers $headers -OutFile $zip -UseBasicParsing
          Expand-Archive -LiteralPath $zip -DestinationPath $tmp -Force
          $root = Get-ChildItem $tmp | Where-Object { $_.PSIsContainer } | Select-Object -First 1
          if (-not $root) { throw "zipball root not found" }
          New-Item -ItemType Directory -Force -Path $env:GITHUB_WORKSPACE | Out-Null
          Get-ChildItem -LiteralPath $root.FullName -Force | Move-Item -Destination $env:GITHUB_WORKSPACE -Force

      - name: Run inventory (Strict mode)
        shell: pwsh
        run: |
          pwsh -NoProfile -File "scripts/g5/inventory.ps1" -Strict

      - name: Upload inventory artifact
        uses: actions/upload-artifact@v4
        with:
          name: inventory-${{ github.sha }}
          path: |
            _inventory/hashes.csv
            _inventory/changes.txt
          if-no-files-found: error

      - name: Persist to main via API (only on push to main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const paths = ['_inventory/hashes.csv','_inventory/changes.txt'];
            for (const p of paths){
              const content = fs.readFileSync(p);
              const res = await github.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo:  context.repo.repo,
                path:  p,
                message: `ci: update ${p} (${context.sha.slice(0,7)})`,
                content: content.toString('base64'),
                branch: 'main',
                committer: { name:'github-actions[bot]', email:'41898282+github-actions[bot]@users.noreply.github.com' },
                author:    { name:'github-actions[bot]', email:'41898282+github-actions[bot]@users.noreply.github.com' }
              });
            }
