name: KLC Smoke
on:
  push:
    branches: [ '**' ]
  pull_request:

jobs:
  klc-smoke:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Smoke log with kobong_logger_cli
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $cli = Join-Path $env:GITHUB_WORKSPACE 'tools/kobong_logger_cli/kobong_logger_cli.ps1'
          if (Test-Path $cli) {
            pwsh -NoProfile -NoLogo -File $cli log --level INFO --module ci --action klc-smoke --outcome SUCCESS --message 'CI can log'
          } else {
            New-Item -ItemType Directory -Force -Path "$env:GITHUB_WORKSPACE/logs" | Out-Null
            $rec = @{
              timestamp=(Get-Date).ToString('o');
              level='INFO'; traceId=[guid]::NewGuid().ToString(); module='ci'; action='klc-smoke';
              outcome='DRYRUN'; errorCode=''; message='CLI missing, fallback'
            } | ConvertTo-Json -Compress
            Add-Content -Path "$env:GITHUB_WORKSPACE/logs/apply-log.jsonl" -Value ($rec + [Environment]::NewLine) -Encoding utf8
          }
      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: klc-logs
          path: logs/**
