name: KLC Verify
on:
  pull_request: { branches: [ main ] }
  push:         { branches: [ main ] }
jobs:
  klc-verify:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PowerShell 7
        uses: PowerShell/PowerShell@v1
        with: { pwsh-version: '7.4.x' }
      - name: Run KLC schema check (minimal)
        shell: pwsh
        run: |
          # 스키마 4요소가 포함된 로그/아티팩트가 존재하는지 탐색
          $hits = Get-ChildItem -Recurse -File -Include *.jsonl,*.log -ErrorAction SilentlyContinue |
            Select-String -Pattern 'traceId','durationMs','exitCode','anchorHash' -SimpleMatch
          if(-not $hits){
            Write-Host 'No KLC lines found → soft warning' -ForegroundColor Yellow
            exit 1  # 초기엔 통과(소프트). 정착되면 1로 바꿔 Fail 처리
          } else {
            Write-Host "KLC lines detected: $($hits.Count)" -ForegroundColor Green
          }

