name: Lint GitHub Actions

on:
  pull_request:
  push:
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check       # 주석/체크로 리포팅
          actionlint_flags: -color     # 옵션(선택)
