name: psanalyze
on:
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    name: analyze
    runs-on: windows-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer (errors only, non-blocking)
        uses: microsoft/psscriptanalyzer-action@v1.0
        with:
          path: '".\scripts\**\*.ps1", ".\ops\**\*.ps1", ".\*.ps1"'
          recurse: true
          severity: '"Error"'
          enableExit: false
          output: results.sarif

      - name: Upload SARIF to Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif