name: Release Gate (auto)
on:
  pull_request:
  push:
permissions:
  statuses: write
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.request('POST /repos/{owner}/{repo}/statuses/{sha}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha:   context.sha,
              state: 'success',
              context: 'Release Gate (auto)',
              description: 'base gate OK'
            });
