name: Release Gate (auto)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

concurrency:
  group: release-gate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gate:
    name: Release Gate (auto)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Gate ping
        run: |
          echo "Release Gate active for $GITHUB_REF"
