# NO-SHELL
name: Release Docs (README badge)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to process (e.g., v0.1.5). Leave empty to use latest v*."
        required: false
        default: ""
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme-badge:
    runs-on: ubuntu-latest
    concurrency:
      group: release-docs-${{ github.ref_name || github.run_id }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Update README badge
        id: update
        env:
          TAG_IN: ${{ github.event.inputs.tag }}
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $tag = $env:TAG_IN
          if ([string]::IsNullOrWhiteSpace($tag)) {
            $tag = (git tag --list "v*" --sort=-v:refname | Select-Object -First 1)
            if ([string]::IsNullOrWhiteSpace($tag)) { throw "No semver tag found (v*)" }
          }

          $remote = git config --get remote.origin.url
          if ($remote -match 'github\.com[:/](?<o>[^/]+)/(?<r>[^/.]+)') { $owner=$Matches.o; $repo=$Matches.r } else { throw "remote parse failed" }

          $badge = ("[![Release](https://img.shields.io/github/v/release/{0}/{1}?display_name=tag&sort=semver)](https://github.com/{0}/{1}/releases/tag/{2})" -f $owner,$repo,$tag)

          $path = 'README.md'
          $orig = (Test-Path $path) ? (Get-Content $path -Raw -Encoding utf8) : ''

          $ownEsc=[regex]::Escape($owner); $repEsc=[regex]::Escape($repo)
          $pattern = '\[!\[Release\]\(https://img\.shields\.io/github/v/release/{0}/{1}\?display_name=tag&sort=semver\)\]\(https://github\.com/{0}/{1}/releases/tag/[^)]+\)' -f $ownEsc,$repEsc
          $rx = [regex]::new($pattern)
          if ($orig -match $pattern) {
            $updated = $rx.Replace($orig, { param([System.Text.RegularExpressions.Match]$m) $badge }, 1)
          } elseif ($orig -match '^# .+') {
            $updated = $orig -replace '^(# .+\R?)', "`$0$badge`n"
          } else {
            $updated = $badge + "`n`n" + $orig
          }

          $updated | Out-File $path -Encoding utf8
          if (git diff --quiet) {
            "did_change=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
            "tag=$tag"        | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
            exit 0
          }

          git config user.name  "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          $head = "docs/readme-badge-$tag"
          git checkout -b $head
          git add README.md
          git commit -m ("docs(readme): update release badge ({0})" -f $tag)
          git push --set-upstream origin $head

          "did_change=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          "tag=$tag"        | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      - name: Open PR and enable auto-merge
        if: steps.update.outputs.did_change == 'true'
        env:
          GH_TOKEN: ${{ secrets.BOT_PR_PAT != '' && secrets.BOT_PR_PAT || github.token }}
          TAG: ${{ steps.update.outputs.tag }}
        shell: bash
        run: |
          set -e
          head="docs/readme-badge-${TAG}"
          if ! gh pr create --title "docs(readme): update release badge (${TAG})" --body "- Auto-updated Release badge." --base main --head "$head"; then
            echo "::warning::PR create failed (likely policy blocking GitHub Actions bot). Leaving branch $head for manual review."
            exit 0
          fi
          pr=$(gh pr view "$head" --json number -q .number || echo "")
          if [ -n "$pr" ]; then
            gh pr merge "$pr" --auto --squash --delete-branch || true
          fi