name: Release Gate (light)
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  gate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check SECURITY.md exists
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          $paths = @('SECURITY.md','.github\SECURITY.md','docs\SECURITY.md')
          $hit = $paths | Where-Object { Test-Path -LiteralPath $_ }
          if(-not $hit){ Write-Error "SECURITY.md not found in $($paths -join ', ')" }
          "Found: $($hit -join ', ')" | Out-Host

      - name: Summarize
        uses: actions/github-script@v7
        with:
          script: |
            core.summary
              .addHeading('Release Gate (light)')
              .addList(['SECURITY.md present ✅','KLC Verify required (manual policy) ✅'])
              .write()
