name: Release Gate (strong)
on:
  release:
    types: [published]
jobs:
  gate:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}  # 태그 기준으로 검사
      - name: Set up PowerShell 7
        with: { pwsh-version: "7.4.x" }
      - name: Policy checks
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          # 1) SECURITY.md 존재/비어있지 않은지
          if(-not (Test-Path .\SECURITY.md)){ Write-Error "SECURITY.md missing"; exit 1 }
          if((Get-Content .\SECURITY.md -Raw).Trim().Length -lt 50){ Write-Error "SECURITY.md too small"; exit 1 }

          # 2) 릴리즈 노트에 KLC 1행 존재
          $body = gh release view $env:TAG_NAME --json body -q .body
          if(-not $body -or -not ($body -match "KLC \| traceId=")){ Write-Error "KLC one-liner missing"; exit 1 }

          # 3) 브랜치 보호: strict + reviews>=1 + Required에 'KLC Verify' 포함
          $bp = gh api repos/:owner/:repo/branches/main/protection | ConvertFrom-Json
          if(-not $bp.required_status_checks.strict){ Write-Error "strict=false"; exit 1 }
          if($bp.required_pull_request_reviews.required_approving_review_count -lt 1){ Write-Error "reviews<1"; exit 1 }
          $ctx = @($bp.required_status_checks.contexts)
          if(-not ($ctx -contains 'KLC Verify')){ Write-Error "'KLC Verify' not required"; exit 1 }

          Write-Host "Release gate strong: OK" -ForegroundColor Green

