# NO-SHELL
name: Release on Tag (ops)
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name to release (e.g. v0.1.1)"
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create or update GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # gh CLI uses GH_TOKEN
        run: |
          set -e
          tag="${{ github.event.inputs.tag }}"
          if [ -z "$tag" ]; then
            tag="${GITHUB_REF#refs/tags/}"
          fi
          if gh release view "$tag" >/dev/null 2>&1; then
            gh release edit "$tag" --latest
          else
            gh release create "$tag" --generate-notes
          fi