name: z10-ak-exec-smoke
on:
  issue_comment: { types: [created] }
permissions:
  issues: write
jobs:
  t:
    runs-on: windows-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner, repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: 'exec loader ✅'
            });
