openapi: 3.1.0
info:
  title: kobong-orchestrator KO
  version: 0.1.0
paths:
  /healthz:
    get:
      summary: Healthz
      operationId: healthz_healthz_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /readyz:
    get:
      summary: Readyz
      operationId: readyz_readyz_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /livez:
    get:
      summary: Livez
      operationId: livez_livez_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/v1/ping:
    get:
      tags:
      - basic
      summary: Ping
      operationId: ping_api_v1_ping_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/v1/echo:
    post:
      tags:
      - basic
      summary: Echo
      operationId: echo_api_v1_echo_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EchoIn'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/sum:
    post:
      tags:
      - basic
      summary: Sum Numbers
      operationId: sum_numbers_api_v1_sum_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SumIn'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/version:
    get:
      tags:
      - basic
      summary: Version
      operationId: version_api_v1_version_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    EchoIn:
      properties:
        text:
          type: string
          maxLength: 10000
          minLength: 0
          title: Text
        meta:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Meta
      type: object
      required:
      - text
      title: EchoIn
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    SumIn:
      properties:
        numbers:
          items:
            type: number
          type: array
          title: Numbers
      type: object
      required:
      - numbers
      title: SumIn
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
